version: '3'

services:
  mongo:
    image: mongo:3.4-jessie
    ports:
      - 27017:27017
    expose:
      - 27017
    container_name: mongo
    network_mode: host

  eureka:
    build: eureka/
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8761:8761

  config:
    build: config/
    restart: always
    network_mode: "host"
    image: demo-config-service
    hostname: localhost
    ports:
      - 8888:8888

  zuul:
    build: zuul/
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8761:8761

  user:
    build: user/
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8081:8081
    depends_on:
      - config
      - eureka
      - mongo
      - zuul